---
version: '3'
services:

  jekyll:
    image: ruby:3.4
    working_dir: /src
    environment:
      BUNDLE_PATH: /vendor
    command: >
      sh -c '
        bundle &&
        bundle exec jekyll serve --host 0.0.0.0 --port 4000
      '
    ports:
      - "4000:4000"
    volumes:
      - .:/src
      - vendor:/vendor

volumes:
  vendor:
